### PR TITLE
chore(hychain): bug fixes

### PR DESCRIPTION
**Pull request by anthonyra**
### TL;DR

Updated Hychain role with improved installation process, metrics collection, and standardized task structure.

### What changed?

- Removed unnecessary README and handler files
- Updated default variables and removed vars/main.yml
- Improved installation process with better file handling and systemd service creation
- Added metrics collection functionality
- Standardized task structure across install, uninstall, start, stop, and restart commands
- Updated templates for systemd service and metrics collector
- Aligned Hychain role structure with other roles like Presearch and Storagechain

### How to test?

1. Run the Hychain role with the `install` command
2. Verify that the Hychain service is installed and running
3. Check that metrics are being collected correctly
4. Test the `start`, `stop`, `restart`, and `uninstall` commands
5. Ensure that the metrics collection is properly removed during uninstallation

### Why make this change?

This change improves the overall structure and functionality of the Hychain role, making it more consistent with other roles in the project. It adds important features like metrics collection and improves the installation and management process, resulting in a more robust and maintainable role.

### CODE REVIEW

**Comment by anthonyra** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/deeep-network/ansible_collections/111?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#111** <a href="https://app.graphite.dev/github/pr/deeep-network/ansible_collections/111?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#49** <a href="https://app.graphite.dev/github/pr/deeep-network/ansible_collections/49?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @anthonyra and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by alex-klikatech** [comment]
Hi @anthonyra,
Could you please describe these points in more detail:
Improved installation process with better file handling and systemd service creation
Standardized task structure across install, uninstall, start, stop, and restart commands
Aligned Hychain role structure with other roles like Presearch and Storagechain

**Comment by anthonyra** [comment]
A lot of these comments are AI generated when looking at the diff for the PR by the way.

> Improved installation process with better file handling and systemd service creation

One of the bigger changes of this PR was essentially parsing their `install.sh` script to a pure Ansible script. The reason for this is control - if they update the install script with new logic and our code pull it directly and runs it. We could do something and not even know which could result in issues. (for example, they default to the latest version everytime so passing in a version didn't do anything) Also the more `ansible.builtin.shell` and `ansbile.builtin.command` we use the less idempotence we have. Meaning each run of the script could result in different "results" even if the results should be the same. The methods implemented also provides checksum checking and A/B upgrades capabilities.

> Standardized task structure across install, uninstall, start, stop, and restart commands

While performing the tests for Hychain I noticed some changes needed for these tasks and attempted to align them to ensure we DRO (don't repeat ourselves)

> Aligned Hychain role structure with other roles like Presearch and Storagechain

Some of the changes noted, also were required to be changed in Presearch and Storagechain. I opted to do the changes in one PR here vs a lot of littles ones to be more atomic. Ideally we should be getting to a point where we won't need to change the structure of different roles with a PR of another.

**Comment by alex-klikatech** [comment]
Am I correct in understanding that we need to merge your changes into our branches and continue working according to the current model?

**Comment by anthonyra** [comment]
@alex-klikatech This PR is stacked on top of yours, which means that when I merge mine via graphite it'll merge yours first than mine. I believe metrics is still required to be completed before this. If you add metrics to your PR I can "restack" to pull it into mine.

**Comment by anthonyra** [comment]
### Merge activity

* **Sep 26, 3:23 PM EDT**: @anthonyra started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/deeep-network/ansible_collections/111).

**Pull request merged**
